version: '3.9'
services:
  express:
    container_name: video-express2
    image: video-express:latest
    build:
      context: .
      dockerfile: Dockerfile.express
    ports:
      - 3001:3000
    volumes:
      - video_express_node:/app/node_modules
      - .:/app

    tty: true
    stdin_open: true
    networks:
      - default

  mongodb:
    image: mongo:latest
    container_name: mongodb2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
    - ./database-data:/data/db # This is necessary to start mongodb

  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express2
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017

volumes:
  video_dev_node_modules:
  video_express_node:
  transcoded_videos:
  thumbnails:


